name: My First Workflow
on: workflow_dispatch

jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - name: List all files
              run: ls -la
            - name: Print Working Directory
              run: pwd
            - name: Create JS File
              run: echo "console.log('Hello, World!');" > app.js
            - name: List all files
              run: ls -la
            - name: Display File Content
              run: node app.js
